live_config_reload: true

window:
  opacity: 0.85
  padding:
    x: 18
    y: 16
  dynamic_padding: false
  # decorations: none


  dimensions:
    columns: 75
    lines: 25

font:
  normal:
    family: "SFMono Nerd Font"
    style: Regular
  size: 15.0
