#!/usr/bin/env bash

## Files and cmd
FILE="/tmp/eww_launch.xyz"
EWW="$HOME/.local/bin/eww/eww -c $HOME/.dotfiles/nix.wip/assets/eww/bar"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets
run_eww() {
	${EWW} open-many \
		bar
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	run_eww && bspc config -m LVDS-1 top_padding 49
else
	${EWW} close-all && killall eww
	rm "$FILE"
fi
