"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$hg_branch\
$fill\
\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$guix_shell\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
\
$sudo\
$cmd_duration\
$jobs\
$time\
$line_break\
$battery\
$status\
$os\
$container\
$shell\
$character
"""

[fill]
symbol = " "

[username]
format = '[$user](bright-black bold)'
disabled = false
show_always = true

[hostname]
ssh_only = false
style = "white dimmed"
format = '[@]($style)[$ssh_symbol]($style)[$hostname]($style):'
disabled = false

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol ]($style)"

[git_metrics]
disabled = false


# =============================== #
# ============ Right ============ #
# =============================== #

[cmd_duration]
format = "[$duration ]($style)"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"


# ============== Package ============== #
[package]
format = '[$symbol($version )]($style) '

# ============== Languages specific ============== #
[bun]
format = "[$symbol($version )]($style)"

[buf]
format = "[$symbol($version )]($style)"

[cmake]
format = "[$symbol($version )]($style)"

[cobol]
format = "[$symbol($version )]($style)"

[crystal]
format = "[$symbol($version )]($style)"

[daml]
format = "[$symbol($version )]($style)"

[dart]
format = "[$symbol($version )]($style)"

[deno]
format = "[$symbol($version )]($style)"

[dotnet]
format = "[$symbol($version )(🎯 $tfm )]($style)"

[elixir]
format = '[$symbol($version )]($style)'

[elm]
format = '[$symbol($version )]($style)'

[erlang]
format = '[$symbol($version )]($style)'

[golang]
format = '[$symbol($version )]($style)'

[helm]
format = '[$symbol($version )]($style)'

[julia]
format = '[$symbol($version )]($style)'

[kotlin]
format = '[$symbol($version )]($style)'

[lua]
format = '[$symbol($version )]($style)'

[meson]
format = '[$symbol($version )]($style)'

[nim]
format = '[$symbol($version )]($style)'

[nodejs]
format = '[$symbol($version )]($style)'
detect_extensions =	[]

[ocaml]
format = '[$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[perl]
format = '[$symbol($version )]($style)'

[php]
format = '[$symbol($version )]($style)'

[pulumi]
format = '[$symbol($version )$stack]($style)'

[purescript]
format = '[$symbol($version )]($style)'

[python]
format = '[$symbol($version )]($style)'

[raku]
format = '[$symbol($version )]($style)'

[red]
format = '[$symbol($version )]($style)'

[rlang]
format = '[$symbol($version )]($style)'

[ruby]
format = '[$symbol($version )]($style)'

[rust]
format = '[$symbol($version )]($style)'

[swift]
format = '[$symbol($version )]($style)'

[vagrant]
format = '[$symbol($version )]($style)'

[vlang]
format = '[$symbol($version )]($style)'

[zig]
format = '[$symbol($version )]($style)'
