#!/usr/bin/env bash

function get_file_location {
	# cmus-remote -C 'echo {}'
	cmus-remote -Q | grep -P "^file" | sed "s/file //"
}

current_song_location="$(get_file_location)"

image_dest="/tmp/cmus_artwork.jpg"

function update_image {
	[[ -e $image_dest ]] && rm "$image_dest"
	ffmpeg -i "$current_song_location" -an -vcodec copy "$image_dest" -hide_banner -loglevel panic #
	clear

	# clears the terminal
	printf "\ec"

	# Move the cursor up 10000A lines.
	printf '\e[10000A'

	kitty +kitten icat --silent --clear
	kitty +kitten icat --silent --align left --place 40x40@0x0 --scale-up "$image_dest"
}

## to hide the cursor
function cleanup {
	tput cnorm
	clear
}
trap cleanup EXIT
tput civis

update_image

while true; do
	url="$(get_file_location)"
	if [ "$current_song_location" != "$url" ]; then
		current_song_location="$url"
		update_image
	fi
	sleep 1
done
