#!/usr/bin/env bash

function get_file_location {
	# cmus-remote -C 'echo {}'
	cmus-remote -Q | grep -P "^file" | sed "s/file //"
}

current_song_location="$(get_file_location)"

function update_lyrics {
	# clear the terminal
	printf "\ec"

	# Move the cursor up 10000A lines.
	printf '\e[10000A'

	"$HOME/repos/MusicLyrics/dist/lib/cmus-api.js"
}

## to hide the cursor
function cleanup {
	tput cnorm
	clear
}
trap cleanup EXIT
tput civis

update_lyrics

while true; do
	url="$(get_file_location)"
	if [ "$current_song_location" != "$url" ]; then
		current_song_location="$url"
		update_lyrics
	fi
	sleep 1
done
