#!/usr/bin/env bash

. "$SCRIPTS/utils.sh"

version=1.0.0

verbose=0
backup=1

LONGOPTS=no-backup,verbose,help
OPTIONS=Bvh

PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
eval set -- "$PARSED"

while true; do
	case "$1" in
	-B | --no-backup)
		backup=0
		;;
	-v | --verbose)
		verbose=1
		shift
		;;
	-h | --help)
		echo -e ""
		echo -e "  ${BOLD}Usage:${END_BOLD}    $(basename "$0") ${YELLOW}[${B_RED}options${DARK_GRAY}...${YELLOW}]${RESET}"
		echo -e "  ${BOLD}Version:${RESET}  ${YELLOW}$version${RESET}"
		echo -e ""
		echo -e "  ${BOLD}Description:${RESET}"
		echo -e ""
		echo -e "    ${B_GRAY}Convert FLAC audio file in \$PWD to mp3.${RESET}"
		echo -e ""
		echo -e "  ${BOLD}Options:${RESET}"
		echo -e ""
		echo -e "    ${BLUE}-h${RESET}, ${BLUE}--help${RESET}       ${B_RED}-${RESET} Show this help and exit."
		echo -e "    ${BLUE}-v${RESET}, ${BLUE}--verbose${RESET}    ${B_RED}-${RESET} Explain what is being done."
		echo -e "    ${BLUE}-B${RESET}, ${BLUE}--no-backup${RESET}  ${B_RED}-${RESET} Don't create a backup before converting."
		echo -e ""
		exit 0
		;;
	--)
		shift
		break
		;;
	*)
		echo -e "${RED}Error:${RESET} Programming error"
		exit 3
		;;
	esac
done

function print() {
	declare _preset
	_text=$1

	if [ -n "$2" ]; then
		_text=$2
		_level=$1

		case "$_level" in
		info)
			_preset="${CYAN}Info${YELLOW}:${RESET} "
			;;
		success)
			_preset="${GREEN}Success${YELLOW}:${RESET} "
			;;
		warning)
			_preset="${YELLOW}Warning${B_RED}:${RESET} "
			;;
		error)
			_preset="${RED}Error${YELLOW}:${RESET} "
			;;
		error_bg)
			_preset="${B_RED_BG}Error${RESET}${YELLOW}:${RESET} "
			;;
		*)
			print error "Invalid print option"
			exit 3
			;;
		esac
	fi

	echo -e "${_preset}$_text"
}

function p() {
	if ((verbose == 1)); then
		print "$1" "$2"
	fi
}

flac_files="$(fd -tf ".*\.flac" "$PWD")"

if [[ -z $flac_files ]]; then
	p warning "no flac files to convert. Exiting..."
	exit 0
fi

if ((backup == 1)); then
	[[ ! -d "$PWD"/backup ]] && {
		mkdir "$PWD/backup" &&
			p info "created the backup folder."
	}

	cp "$PWD"/*.flac "$PWD/backup" &>/dev/null &&
		p success "created backup."
fi

[[ ! -d "$PWD"/flac ]] && {
	mkdir "$PWD/flac" &&
		p info "created the flac folder (a temp folder)."
}

mv "$PWD"/*.flac "$PWD/flac" &&
	p info "moved flac files to ./flac."

[[ ! -d "$PWD"/mp3 ]] && {
	mkdir "$PWD/mp3" &&
		p info "created the mp3 folder (a temp folder)."
}

for file in $flac_files; do
	filename=$(basename "$file" .flac)
	ffmpeg \
		-i "$file" \
		-ab 320k \
		-map_metadata 0 \
		-id3v2_version 3 \
		"$PWD"/mp3/"$filename".mp3 &&
		p success "done \"${UNDERLINE}$filename${END_UNDERLINE}\"." ||
		p error "something worng happened while converting $filename."
done

mv "$PWD"/mp3/* "$PWD" &&
	p info "moved created files to \$PWD."
rm -rf "$PWD/{mp3,flac}" &&
	p info "removed ./flac and ./mp3."

p success "done."
