#!/usr/bin/env bash

total="$(free -m | awk '/Mem:/ {print $2}')"
used="$(free -m | awk '/Mem:/ {print $3}')"

free="$(("$total" - "$used"))"

if [ "$1" = "total" ]; then
	echo "$total"
elif [ "$1" = "used" ]; then
	echo "$used"
elif [ "$1" = "free" ]; then
	echo "$free"
fi
