#!/usr/bin/env bash

status="$(nmcli g | rg -o "disconnected")"
essid="$(nmcli c | awk '/wlp3s0/ {print ($1)}')"

if [ "$status" ]; then
	icon=""
	text=""
	col="#575268"
else
	icon=""
	text="${essid}"
	col="#a1bdce"
fi

if [[ "$1" == "--COL" ]]; then
	echo "$col"
elif [[ "$1" == "--ESSID" ]]; then
	echo "$text"
elif [[ "$1" == "--ICON" ]]; then
	echo "$icon"
fi
