local c = require("catppuccin.palettes").get_palette "mocha"

-- MOCHA'S COLOR PALETTE FOR REFERENCE
-- rosewater = "#F5E0DC",
-- pink = "#F5C2E7",
-- flamingo = "#F2CDCD",
-- mauve = "#CBA6F7",
-- red = "#F38BA8",
-- maroon = "#EBA0AC",
-- peach = "#FAB387",
-- yellow = "#F9E2AF",
-- green = "#A6E3A1",
-- teal = "#94E2D5",
-- sky = "#89DCEB",
-- sapphire = "#74C7EC",
-- blue = "#89B4FA",
-- lavender = "#B4BEFE",

-- text = "#CDD6F4",
-- subtext1 = "#BAC2DE",
-- subtext0 = "#A6ADC8",
-- overlay2 = "#9399B2",
-- overlay1 = "#7F849C",
-- overlay0 = "#6C7086",
-- surface2 = "#585B70",
-- surface1 = "#45475A",
-- surface0 = "#313244",

-- base = "#1E1E2E",
-- mantle = "#181825",
-- crust = "#11111B",

return {
  rosewater = c.rosewater,
  pink = c.pink,
  flamingo = c.flamingo,
  mauve = c.mauve,
  red = c.red,
  maroon = c.maroon,
  peach = c.peach,
  yellow = c.yellow,
  green = c.green,
  teal = c.teal,
  sky = c.sky,
  sapphire = c.sapphire,
  blue = c.blue,
  lavender = c.lavender,

  light_green = c.teal,
  light_blue = c.sapphire,
  light_yellow = c.rosewater,
  light_orange = c.flamingo,
  orange = c.peach,
  purple = c.mauve,
  violet = c.lavender,
  cyan = c.sky,

  white = c.text,
  black = c.crust,

  text = c.text,
  subtext1 = c.subtext1,
  subtext0 = c.subtext0,
  overlay2 = c.overlay2,
  overlay1 = c.overlay1,
  overlay0 = c.overlay0,
  surface2 = c.surface2,
  surface1 = c.surface1,
  surface0 = c.surface0,

  base = c.base,
  mantle = c.mantle,
  crust = c.crust,
}
