#!/usr/bin/env bash

get_status() {
	s=$1
	if [ "$s" = "Playing" ]; then
		echo ""
	else
		echo ""
	fi
}

get_length_sec() {
	len=$1
	if [ -z "$len" ]; then
		echo 0
	else
		bc <<<"$len / 1000000"
	fi
}

get_length_time() {
	len=$1
	if [ -n "$len" ]; then
		len=$(bc <<<"$len / 1000000 + 1")
		date -d@"$len" +%M:%S
	else
		echo ""
	fi
}

get_position() {
	pos=$1
	len=$2
	if [ -n "$pos" ]; then
		bc -l <<<"$pos / $len * 100"
	else
		echo 0
	fi
}

get_position_time() {
	pos=$1
	len=$2
	if [ -n "$pos" ]; then
		date -d@"$(bc <<<"$pos / 1000000")" +%M:%S
	else
		echo ""
	fi
}

get_cover() {
	mkdir -p "$HOME/.cache/eww_covers"
	cd "$HOME/.cache/eww_covers" || exit

	IMGPATH="$HOME/.cache/eww_covers/cover_art.png"

	while true; do
		MPD_IS_PLAYING="$(mpc | rg -c "\playing\]")"
		COVER_URL="$(playerctl metadata mpris:artUrl 2>/dev/null)"

		if ((MPD_IS_PLAYING == 1)); then
			ART_WORK="$("$HOME/.local/bin/mpd_get_artwork")"
			echo "${ART_WORK}"
		elif [[ -n "$COVER_URL" ]]; then
			echo "$COVER_URL"
		elif [[ "$COVER_URL" = https* ]]; then
			if [ ! -e "$HOME/.cache/eww_covers/$(basename "$COVER_URL")" ]; then
				wget -N "$COVER_URL" -o /dev/null
			fi

			rm "$IMGPATH"
			ln -s "$(basename "$COVER_URL")" "$IMGPATH"

			echo "$IMGPATH"
		else
			echo "assets/music.png"
		fi

		sleep 1
	done
}

sanitize() {
	echo "$1" | sed 's/"/\"/g'
}

if [[ "$1" == "cover" ]]; then
	get_cover
else
	playerctl -F metadata -f '{{title}}\{{artist}}\{{status}}\{{position}}\{{mpris:length}}\' 2>/dev/null | while IFS="$(printf '\\')" read -r title artist status position len; do
		jaq --null-input \
			-r -c \
			--arg artist "$(sanitize "$artist")" \
			--arg title "$(sanitize "$title")" \
			--arg status "$(get_status "$status")" \
			--arg pos "$(get_position "$position" "$len")" \
			--arg pos_time "$(get_position_time "$position" "$len")" \
			--arg length "$(get_length_time "$len")" \
			'{"artist": $artist, "title": $title, "status": $status, "position": $pos, "position_time": $pos_time, "length": $length}'
	done
fi
