#!/usr/bin/env bash

volicons=("" "" "")

vol() {
	if [[ $1 == "SINK" ]]; then
		pulsemixer --get-volume | awk '{print $1}'
	elif [[ $1 == "SOURCE" ]]; then
		pacmd list-sources | grep -P "^\svolume:" | tail -n 1 | awk -F '[/]' '{print int($2)}'
	fi
}
ismuted() {
	pacmd list-sinks | rg "muted: yes"
	echo $?
}
setvol() {
	if [[ $1 == "SINK" ]]; then
		pactl set-sink-mute @DEFAULT_SINK@ 0
		pactl set-sink-volume @DEFAULT_SINK@ "$(awk -v n="$2" 'BEGIN{print (n / 100)}')"
	elif [[ $1 == "SOURCE" ]]; then
		pactl set-source-mute @DEFAULT_SOURCE@ 0
		pactl set-source-volume @DEFAULT_SOURCE@ "$(awk -v n="$2" 'BEGIN{print (n / 100)}')"
	fi
}
setmute() {
	if [[ $1 == "SINK" ]]; then
		pactl set-sink-mute @DEFAULT_SINK@ toggle
	elif [[ $1 == "SOURCE" ]]; then
		pactl set-source-mute @DEFAULT_SOURCE@ toggle
	fi
}

if [ "$1" = "mute" ]; then
	if [ "$2" != "SOURCE" ] && [ "$2" != "SINK" ]; then
		echo "Can only mute SINK or SOURCE"
		exit 1
	fi
	setmute "$2"
elif [ "$1" = "setvol" ]; then
	if [ "$2" != "SOURCE" ] && [ "$2" != "SINK" ]; then
		echo "Can only set volume for SINK or SOURCE"
		exit 1
	elif [ "$3" -lt 1 ] || [ "$3" -gt 100 ]; then
		echo "Volume must be between 1 and 100"
		exit 1
	fi
	setvol "$2" "$3"
else
	# initial values
	lvl=$(awk -v n="$(vol "SINK")" 'BEGIN{print int(n/34)}')
	ismuted=$(ismuted "SINK")

	if [ "$ismuted" = 1 ]; then
		icon="${volicons[$lvl]}"
		[[ -z $icon ]] && icon="${volicons[2]}"
	else
		icon=""
	fi
	echo '{ "icon": "'"$icon"'", "percent": "'"$(vol "SINK")"'", "microphone": "'"$(vol "SOURCE")"'" }'

	# event loop
	pactl subscribe | rg --line-buffered "change" | while read -r _; do
		lvl=$(awk -v n="$(vol "SINK")" 'BEGIN{print int(n/34)}')
		ismuted=$(ismuted "SINK")

		if ((ismuted == 1)); then
			icon="${volicons[$lvl]}"
			[[ -z $icon ]] && icon="${volicons[2]}"
		else
			icon=""
		fi
		echo '{ "icon": "'"$icon"'", "percent": "'"$(vol "SINK")"'", "microphone": "'"$(vol "SOURCE")"'" }'
	done
fi
