add_newline = false

format = """
$directory\
$git_branch\
$cmd_duration\
$line_break\
$jobs\
$battery\
$python\
$character"""

[line_break]
disabled = true

[python]
format = '[(\($virtualenv\) )]($style)'
