#!/usr/bin/env bash

is_charging=$1
current_percentage=$(cat /sys/class/power_supply/BAT1/capacity)

NOTIFICATION_ID=4215

if ((is_charging == 1)); then
	dunstify \
		"Charging" \
		"$current_percentage% of battery charged." \
		-i "$HOME/.local/share/icons/battery-charging.png" \
		-u low \
		-r "$NOTIFICATION_ID"
	canberra-gtk-play -i power-plug
elif ((is_charging == 0)); then
	dunstify \
		"Disconnected" \
		"$current_percentage% of battery remaining." \
		-i "$HOME/.local/share/icons/battery.png" \
		-u low \
		-r "$NOTIFICATION_ID"
	canberra-gtk-play -i power-unplug
fi
