#!/usr/bin/env bash

is_charging=$1
current_percentage=$(acpi | grep -Po '[0-9]{1,3}(?=%)')

# FIXME: Doesn't override!!
NOTIFICATION_ID=80008

if ((is_charging == 1)); then
	notify-send "Charging" "$current_percentage% of battery charged." -u low -i "$HOME/.local/share/icons/battery-charging.png" -t 5000 -r "$NOTIFICATION_ID"
	paplay "/usr/share/sounds/Yaru/stereo/power-plug.oga"
elif ((is_charging == 0)); then
	notify-send "Disconnected" "$current_percentage% of battery remaining." -u low -i "$HOME/.local/share/icons/battery.png" -t 5000 -r "$NOTIFICATION_ID"
	paplay "/usr/share/sounds/Yaru/stereo/power-unplug.oga"
fi
