#!/usr/bin/env bash

# for the cron job
export XDG_RUNTIME_DIR="/run/user/1000"

BAT_CACHE_DIR=/tmp/battery
LOW_NOTF_FILE="$BAT_CACHE_DIR/low"
CHARGED_FILE="$BAT_CACHE_DIR/full"

WARNING_LEVELS=(20 5 3)
CHARGED_ON=95

[[ ! -d "$BAT_CACHE_DIR" ]] && mkdir "$BAT_CACHE_DIR"
[[ ! -f "$LOW_NOTF_FILE" ]] && touch "$LOW_NOTF_FILE"

current_percentage=$(acpi | grep -Po '[0-9]{1,3}(?=%)')
is_discharging=$(acpi | grep -c "Discharging")

notified_for=$(cat "$LOW_NOTF_FILE")

NOTIFICATION_ID=4215

if
	[[ "$current_percentage" -ge "$CHARGED_ON" &&
		"$is_discharging" -eq 0 &&
		! -f "$CHARGED_FILE" ]]
then
	dunstify "Battery Charged" "$current_percentage% you can unplug the charger" \
		-i "$HOME/.local/share/icons/battery-charging.png" \
		-r "$NOTIFICATION_ID"
	canberra-gtk-play -i complete.oga
	touch "$CHARGED_FILE"
elif [[ "$is_discharging" -eq 1 && -f "$CHARGED_FILE" ]]; then
	rm "$CHARGED_FILE"
fi

# Warning on discharge
for warning_level in "${WARNING_LEVELS[@]}"; do
	should_notify=1
	for item in $notified_for; do
		[[ "$warning_level" == "$item" ]] && should_notify=0
	done

	if [[ "$is_discharging" -eq 1 &&
		"$current_percentage" -le $warning_level &&
		$should_notify -eq 1 ]]; then
		dunstify "Low battery" "$current_percentage% of battery remaining" \
			-i "$HOME/.local/share/icons/battery-alert.png" \
			-u critical \
			-r "$NOTIFICATION_ID"
		canberra-gtk-play -i dialog-error --volume 25.0
		notified_for+=("$warning_level")
	fi
done

if [[ "$is_discharging" -eq 0 && "${#notified_for[@]}" -gt 0 ]]; then
	notified_for=()
fi

echo "${notified_for[*]}" >"$LOW_NOTF_FILE"
