#!/usr/bin/env bash

# TODO: notify

case "$1" in
up)
	brillo -u 150000 -A 10
	# brightness=$(light)
	# dunstify -a "BRIGHTNESS" "Increasing to $brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
	;;
down)
	brillo -u 150000 -U 10
	# brightness=$(light)
	# dunstify -a "BRIGHTNESS" "Decreasing to $brightness%" -h int:value:"$brightness" -i display-brightness-symbolic -r 2593 -u normal
	;;
esac
