#!/usr/bin/env bash

NOTIF_ID=2592

icons=(brightness-low brightness-medium brightness-high)

function notify {
	brightness="$(awk -v n="$(light)" 'BEGIN{print int(n)}')"
	if ((brightness == 0)); then
		icon="brightness-off"
	else
		icon="${icons[$(awk -v n="$(light)" 'BEGIN{print int(n/34)}')]}"
		[[ -z $icon ]] && icon="${icons[3]}"
	fi
	dunstify -a "BRIGHTNESS" "$brightness %" -h int:value:"$brightness" -i "$HOME/.config/dunst/assets/ui/${icon}.svg" -r "$NOTIF_ID" -u normal
}

case "$1" in
up)
	brillo -u 150000 -A 10
	notify
	;;
down)
	brillo -u 150000 -U 10
	notify
	;;
esac
