#!/usr/bin/env bash

# TODO: notify

case $1 in
up)
	pactl set-source-mute @DEFAULT_SOURCE@ 0
	pactl set-source-volume @DEFAULT_SOURCE@ +5%
	;;
down)
	pactl set-source-mute @DEFAULT_SOURCE@ 0
	pactl set-source-volume @DEFAULT_SOURCE@ -5%
	;;
mute)
	pactl set-source-mute @DEFAULT_SOURCE@ toggle
	;;
esac
