#!/usr/bin/env bash

version=1.1.0

BOLD="\e[1m"
END_BOLD="\e[22m"
UNDERLINE="\e[4m"
END_UNDERLINE="\e[24m"
REVERSE_TEXT="\e[7m"
END_REVERSE="\e[27m"

BLACK="\e[30m"
BLACK_BG="\e[40m"
WHITE="\e[97m"
WHITE_BG="\e[107m"

RED="\e[31m"
RED_BG="\e[41m"
GREEN="\e[32m"
GREEN_BG="\e[42m"
YELLOW="\e[33m"
YELLOW_BG="\e[43m"
BLUE="\e[34m"
BLUE_BG="\e[44m"
MAGENTA="\e[35m"
MAGENTA_BG="\e[45m"
CYAN="\e[36m"
CYAN_BG="\e[46m"

BRIGHT_GRAY="\e[37m"
BRIGHT_GRAY_BG="\e[47m"
DARK_GRAY="\e[90m"
DARK_GRAY_BG="\e[100m"

BRIGHT_RED="\e[91m"
BRIGHT_RED_BG="\e[101m"
BRIGHT_GREEN="\e[92m"
BRIGHT_GREEN_BG="\e[102m"
BRIGHT_YELLOW="\e[93m"
BRIGHT_YELLOW_BG="\e[103m"
BRIGHT_BLUE="\e[94m"
BRIGHT_BLUE_BG="\e[104m"
BRIGHT_MAGENTA="\e[95m"
BRIGHT_MAGENTA_BG="\e[105m"
BRIGHT_CYAN="\e[96m"
BRIGHT_CYAN_BG="\e[106m"

RESET="\e[0m"

in_place=0

LONGOPTS=in-place,help
OPTIONS=i,h

PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
eval set -- "$PARSED"

while true; do
	case "$1" in
	-h | --help)
		echo -e ""
		echo -e "  ${BOLD}Usage:${END_BOLD}    $(basename "$0") ${YELLOW}[${BRIGHT_RED}OPTIONS${DARK_GRAY}...${YELLOW}]${RESET} ${GREEN}ARGUMENTS${WHITE}${RESET}"
		echo -e "  ${BOLD}Version:${RESET}  ${YELLOW}$version${RESET}"
		echo -e ""
		echo -e "  ${BOLD}Description:${RESET}"
		echo -e ""
		echo -e "    ${BRIGHT_GRAY}Compresses a pdf file.${RESET}"
		echo -e ""
		echo -e "  ${BOLD}Arguments:${RESET}"
		echo -e ""
		echo -e "    ${BOLD}${GREEN}Source${WHITE} ${YELLOW}{${BLUE}file${YELLOW}}${RESET}     ${BRIGHT_RED}-${RESET} The file to compress."
		echo -e ""
		echo -e "  ${BOLD}Options:${RESET}"
		echo -e ""
		echo -e "    ${BLUE}-i${RESET}, ${BLUE}--in-place${RESET}    ${BRIGHT_RED}-${RESET} Compress the file in place."
		echo -e "    ${BLUE}-h${RESET}, ${BLUE}--help${RESET}        ${BRIGHT_RED}-${RESET} Show this help."
		echo -e ""
		exit 0
		;;
	-i | --in-place)
		in_place=1
		shift
		;;
	--)
		shift
		break
		;;
	*)
		echo -e "${RED}Error:${RESET} Programming error"
		exit 3
		;;
	esac
done

src="$1"
output="$(basename "$src" .pdf).compressed.pdf"

if [[ ! -f "$src" ]]; then
	echo -e "${RED}Error:${RESET} can't find the provided file."
	exit 1
fi

gs \
	-q \
	-dNOPAUSE \
	-dBATCH \
	-dSAFER \
	-sDEVICE=pdfwrite \
	-dNOTRANSPARENCY \
	-dPDFSETTINGS=/screen \
	-dEmbedAllFonts=true \
	-dSubsetFonts=true \
	-dColorImageDownsampleType=/Bicubic \
	-dColorImageResolution=144 \
	-dGrayImageDownsampleType=/Bicubic \
	-dGrayImageResolution=144 \
	-dMonoImageDownsampleType=/Bicubic \
	-dMonoImageResolution=144 \
	-sOutputFile="$output" \
	"$src"

if ((in_place == 1)); then
	mv "$output" "$src"
fi
