#!/usr/bin/env bash

# TODO: notify

function play_sound {
	sound_file="$HOME/.local/share/sounds/audio-volume-change.oga"
	[[ ! -f $sound_file ]] && cp "$DOTFILES_ASSETS/sounds/audio-volume-change.oga" "$sound_file"
	paplay "$sound_file"
}

case $1 in
up)
	pactl set-sink-mute @DEFAULT_SINK@ 0
	play_sound
	pactl set-sink-volume @DEFAULT_SINK@ +5%
	;;
down)
	pactl set-sink-mute @DEFAULT_SINK@ 0
	play_sound
	pactl set-sink-volume @DEFAULT_SINK@ -5%
	;;
mute)
	pactl set-sink-mute @DEFAULT_SINK@ toggle
	play_sound
	;;
esac
