#!/usr/bin/env bash

# TODO: notify

function play_sound {
	paplay "/usr/share/sounds/Yaru/stereo/audio-volume-change.oga"
}

case $1 in
up)
	amixer -c 1 set Master 9%+ unmute
	play_sound
	;;
down)
	amixer -c 1 set Master 9%- unmute
	play_sound
	;;
mute)
	amixer -c 1 set Master togglemute
	play_sound
	;;
esac
