gui:
  showIcons: true

git:
  paging:
    colorArg: always
    pager: delta --dark --diff-so-fancy --paging=never # TODO:

customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
