lastupdatecheck: 0
recentrepos:
- /home/omareloui/dotfiles
- /home/omareloui/repos/Portfolio
- /home/omareloui/repos/FixSRT
- /home/omareloui/repos/BrainFuckInterpreter
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
