#!/usr/bin/env bash

function get_current {
	mpc --format "$MUSIC_DIR/%file%" current
}

old="$(get_current)"
sleep_duration=1

function update_image {
	printf "\ec" # clear the terminal
	kitty +kitten icat --silent --align left "$(mpd_get_artwork 400)"
	printf "\e[10000A" # move the cursor up 10000 lines
	printf "\eD\eD"    # scroll down
}

update_image

while true; do
	current="$(get_current)"

	if [[ "$current" == "$old" ]]; then
		sleep $sleep_duration
		continue
	fi

	update_image

	# mpc current --wait
	old="$current"
	sleep $sleep_duration
done
