#!/usr/bin/env bash

version=1.0.1

BOLD="\e[1m" END_BOLD="\e[22m"

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"

B_GRAY="\e[37m"
DARK_GRAY="\e[90m"

B_RED="\e[91m"
B_MAGENTA="\e[95m"

RESET="\e[0m"

verbose=0

LONGOPTS=verbose,help
OPTIONS=vh

PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
eval set -- "$PARSED"

while true; do
	case "$1" in
	-v | --verbose)
		verbose=1
		shift
		;;
	-h | --help)
		echo -e ""
		echo -e "  ${BOLD}Usage:${END_BOLD}    $(basename "$0") ${YELLOW}[${B_RED}options${DARK_GRAY}...${YELLOW}]${RESET}"
		echo -e "  ${BOLD}Version:${RESET}  ${YELLOW}$version${RESET}"
		echo -e ""
		echo -e "  ${BOLD}Description:${RESET}"
		echo -e ""
		echo -e "    ${B_GRAY}Update the packages list to back it up.${RESET}"
		echo -e ""
		echo -e "  ${BOLD}Options:${RESET}"
		echo -e ""
		echo -e "    ${BLUE}-h${RESET}, ${BLUE}--help${RESET}       ${B_RED}-${RESET} Show this help and exit."
		echo -e "    ${BLUE}-v${RESET}, ${BLUE}--verbose${RESET}    ${B_RED}-${RESET} Explain what is being done."
		echo -e ""
		echo -e "  ${BOLD}Examples:${RESET}"
		echo -e ""
		echo -e "    ${RED}\$${RESET} ${B_MAGENTA}$(basename "$0")${RESET}"
		echo -e "    ${RED}\$${RESET} ${B_MAGENTA}$(basename "$0")${RESET} -v"
		echo -e ""
		exit 0
		;;
	--)
		shift
		break
		;;
	*)
		echo -e "${RED}Error${YELLOW}:${RESET} Programming error"
		exit 3
		;;
	esac
done

function p() {
	if ((verbose == 1)); then
		echo -e "$1"
	fi
}

[[ -z $BOOTSTRAP_FILES ]] && BOOTSTRAP_FILES="$HOME/.dotfiles/bootstrap"

file="$BOOTSTRAP_FILES/assets/packages.lst"
tmp="$file.tmp"

p "${BLUE}Info${YELLOW}:${RESET} parsing the packages"

pacman -Qqe >"$tmp"
pacman -Qqm >>"$tmp"

{
	sort <"$tmp" | uniq >"$file"
	rm "$tmp"
} && p "${GREEN}Success${YELLOW}:${RESET} created the packages list"
