#!/usr/bin/env bash

function play_sound {
	canberra-gtk-play -i audio-volume-change -d "changevolume"
}

icons=(volume_low volume_medium volume_high)

NOTF_ID=2593

function notify {
	volume=$(amixer get Master | awk -F"[][]" '/Left:/ {print $2}')
	volume_on=$(amixer get Master | awk -F"[][]" '/Left:/ {print $4}')
	# volume=$(pamixer --get-volume)
	# muted=$(pamixer --get-mute)
	if [[ $volume_on == "off" ]]; then
		icon=volume_muted
	elif ((volume == 0)); then
		icon=volume_off
	else
		index="$(echo "($volume / 34)" | bc)"
		icon="${icons[$index]}"
		[[ -z $icon ]] && icon="${icons[2]}"
	fi
	dunstify \
		-a "VOLUME" \
		"Volume" \
		"$volume %" -h int:value:"$volume" \
		-i "$HOME/.config/dunst/assets/ui/${icon}.svg" \
		-r $NOTF_ID \
		-u normal
}

case $1 in
up)
	amixer -D pipewire set Master unmute
	amixer -D pipewire set Master 5%+
	# pactl set-sink-mute @DEFAULT_SINK@ 0
	# pactl set-sink-volume @DEFAULT_SINK@ +5%
	notify
	play_sound
	;;
down)
	amixer -D pipewire set Master unmute
	amixer -D pipewire set Master 5%-
	# pactl set-sink-mute @DEFAULT_SINK@ 0
	# pactl set-sink-volume @DEFAULT_SINK@ -5%
	notify
	play_sound
	;;
mute)
	amixer -D pipewire set Master toggle
	# pactl set-sink-mute @DEFAULT_SINK@ toggle
	notify
	play_sound
	;;
esac
