#!/usr/bin/env bash

wp="$1"

if [[ -z $wp ]]; then
	wp="$(fd . -p "$HOME/.wallpaper/current" -It f -d 1 | shuf --random-source=/dev/urandom -n 1)"
fi

hyperpaper_file="$HOME/.config/hypr/hyprpaper.conf"

{
	echo "preload = $wp"
	echo ""
	echo "wallpaper = eDP-1,$wp"
	echo "wallpaper = HDMI-A-1,$wp"
} >"$hyperpaper_file"

# echo -e " HDMI-A-1,$wp\nwallpaper = ,$wp\nsplash = true" >"$hyperpaper_file"

# Close previous hyprpaper instance
ps -a | awk '/hyprpaper/ {print $1}' | xargs -n1 kill

hyprpaper
